### ISSUE TITLE
WD MyCloud Home App

### ISSUE THREAD

**Issue by willone2** [bhanupratapys/dnswarden#11]
Hey, I recently got a WD Cloud NAS, but when trying to connect to it through the Android app (https://play.google.com/store/apps/details?id=com.wdc.mycloud&hl=en_US) it cannot connect, I've linked a screenshot. When disconnecting from the DNS it works fine.

![Attatchment](https://user-images.githubusercontent.com/11077351/68057308-65fc6800-fced-11e9-9bd4-93eefadbe3a7.jpg)

**Comment by bhanupratapys** [comment]
Removed couple of suspected domains which might be causing this error, can you try it now ? I'm flying blind here. Without signing into the app, I can't do much.

**Comment by willone2** [comment]
After looking into this a bit further and discovering it also didnt work on the unblocked DNS, I've found that the app doesn't work with any custom DNS servers at all. Sorry for the confusion !
