### ISSUE TITLE
Another blocklist | oisd.nl

### ISSUE THREAD

**Issue by mucke5** [bhanupratapys/dnswarden#12]
Request for extension or provision of a separate DoH/DoT as an adblock list using the following block list
[oisd.nl](https://oisd.nl)
>Thanks in advance

**Comment by bhanupratapys** [comment]
Hey there, that is a very good filterlist which is also included in adblock-dns. What is the usecase just to enable this list separately ?

**Comment by mucke5** [comment]
Hey, was that filter list already in adblock-dns or did you add it now? That's not quite clear to me now.
Will this list be applied in adult-filter-dns #8 as soon as it is finished? Wait for DoT deployment...

**Comment by bhanupratapys** [comment]
This list has been included since couple of months. And yes, adult-filter dns is gonna have same filterlist as adblock dns and along with adult filterlists.

**Comment by bhanupratapys** [comment]
> Hey, was that filter list already in adblock-dns or did you add it now? That's not quite clear to me now.
> Will this list also be applied to adult-filter-dns #8 once it is finished? Wait for DoT deployment...

Adult-filter dns is finally implemented, [read me page](https://github.com/bhanupratapys/dnswarden/blob/master/README.md) should have info regarding it.
