### ISSUE TITLE
Support ECS

### ISSUE THREAD

**Issue by AndrewSmith96** [bhanupratapys/dnswarden#15]
Hello, is it possible to support ecs for atleast one of the dns protocols?

**Comment by bhanupratapys** [comment]
Hi there. ECS most definitely will be helpful while using cdn's. As of now it's not possible for me to support this feature without further tweaking and also would require me to add additional software to implement this. Adding ECS would also generate huge amounts of queries when compared with non-Ecs queries, which I can't handle as of now. What I can do is, filter the queries of adblock and adult-filter dns and forward them to the public resolvers which supports ECS i.e google/quad9

**Comment by bhanupratapys** [comment]
Added ecs support for dnscrypt and dns-over-https, it self resolves as of now. Look [here](https://github.com/bhanupratapys/dnswarden/blob/master/README.md) for more info.

**Comment by AndrewSmith96** [comment]
Thank you, doh is working perfectly. Cdn's performance is better while using ecs enabled dns.
