### ISSUE TITLE
oauth.reddit.com

### ISSUE THREAD

**Issue by beerisgood** [bhanupratapys/dnswarden#17]
This domain (Reddit) got blocked in AdBlock Version and is needed for Reddit.
Please unblock

**Comment by bhanupratapys** [comment]
That's weird, it's already whitelisted [here](https://github.com/dnswarden/blocklist/blob/master/whitelist.txt#L2215). Will look into it.

**Comment by beerisgood** [comment]
Strange indeed. Today the problem is gone, even if I yesterday check that it runs without your DNS fine.

I let this issue open until tommorow and close it if no new problem pop up.

Thanks for your fast answer!

**Comment by bhanupratapys** [comment]
Found the issue and fixed it by reverting to a earlier version. It was a bug introduced in master branch of a resolver software I use, where the resolver sometimes failed to resolve CNAME's in the chain.

**Comment by beerisgood** [comment]
Awesome.

I close this issue then. Problem looks still solved
Thanks!

**Comment by beerisgood** [comment]
Sadly the issue start again

**Comment by bhanupratapys** [comment]
@beerisgood on which type of dns did you encounter this problem on (dot/doh/DNSCrypt/clear-text)? 
Which filter type were you using (adblock/uncensored/adult-filter)?

**Comment by beerisgood** [comment]
Sorry for fast re-locking but the problem start a few minutes again but gone some seconds later again.

@bhanupratapys I use AdBlock DoT in Android 10

**Comment by bhanupratapys** [comment]
This problem should be minimal now. If the client fails to get the answer in the first attempt in adverse conditions, then the subsequent query should be able to get the correct answers without any delay.

**Comment by beerisgood** [comment]
I try it a few times reload but doesn't work. Only after I disable DoT and re-enable it work.

Maybe Android handle something different or doesn't wait enough for the DNS answer.

Anyway it works (again) ^^

**Comment by beerisgood** [comment]
I close the issue now, as it run stable since last time.
Good work!
