### ISSUE TITLE
Avoid setting YouTube into "Restricted Mode" for the Adult Filter?

### ISSUE THREAD

**Issue by lazerl0rd** [bhanupratapys/dnswarden#22]
CleanBrowsing DNS does this too, and I assume it is due to comments being restricted along with a plethora of unnecessary videos being blocked off.

**Comment by IDKwhattoputhere** [comment]
Related: https://github.com/nextdns/metadata/issues/62#issuecomment-584747452

**Comment by bhanupratapys** [comment]
Revived project, should be working properly now.
