### ISSUE TITLE
Asia server is unstable

### ISSUE THREAD

**Issue by What-Zit-Tooya** [bhanupratapys/dnswarden#23]
Hi ,
Im testing your dns - uncensored (Https - asia server) but i get myTelkomsel is cant connect to it's server.
`https://play.google.com/store/apps/details?id=com.telkomsel.telkomselcm`
Its servers (`tdw.telkomsel.com`) sometimes get dns answer `A,servfail` or `AAAA,servfail`

No issue on cloudflare dns or another dns.

Im using Adguard Android on LineageOS 18.1 (android 11)

**Comment by bhanupratapys** [comment]
`tdw.telkomsel.com` should be working now.
