### ISSUE TITLE
Add client to readme

### ISSUE THREAD

**Issue by fusionneur** [bhanupratapys/dnswarden#24]
You can add Invizible Pro to the list of Android clients:
https://github.com/bhanupratapys/dnswarden/blob/master/README.md

More info at: https://f-droid.org/en/packages/pan.alexander.tordnscrypt.stable/

**Comment by bhanupratapys** [comment]
Thanks! 
Added in https://github.com/bhanupratapys/dnswarden/commit/698e51a0bcabbfc2e8d9ceaccf86a57bea47afba.
