### ISSUE TITLE
Incompatible with Anonymized DNSCrypt

### ISSUE THREAD

**Issue by korongmambu** [bhanupratapys/dnswarden#25]
I use `dnswarden-uncensor-sg1-dc` in `dnscrypt-proxy` with anonymized dnscrypt, in `dnscrypt-proxy.toml` I set `skip_incompatible = true`, but `dnswarden-uncensor-sg1-dc` not in used (incompatilbe with the settings). Any plan to make it compatible?

**Comment by bhanupratapys** [comment]
Looks like it is failing on certain relays and working on some relays, for example it worked on `anon-cs-montreal` relay. I've no idea what is causing to fail on some relays.

**Comment by bhanupratapys** [comment]
Closing this, the older dnscrypt servers will cease to exist in few days/weeks as i've moved my entire dns setup to new platform. Stamps for new servers can be found [here](https://github.com/bhanupratapys/dnswarden/tree/master/stamps/dnscrypt).
