### ISSUE TITLE
dnswarden appearing to not being able to block certain domains

### ISSUE THREAD

**Issue by GiddyGoatGaming** [bhanupratapys/dnswarden#26]
So I’ve noticed this for awhile with dnswarden where some domains just won’t get blocked no matter how many blocklists I choose. I noticed this with d3ward which will never block

https://ads-dev.pinterest.com/
https://widgets.pinterest.com/
https://adtago.s3.amazonaws.com/
https://analyticsengine.s3.amazonaws.com/
https://advice-ads.s3.amazonaws.com/
https://affiliationjs.s3.amazonaws.com/
https://advertising.twitter.com/

Ive tested these with and without the whitelist and it’s still the same. I’m not sure if there’s a whitelist that is not visible on the website that is enabled by default but I would like to see these domains blocked as they are blocked by every big Adblock blocklist like Oisd. Thanks🙏.

**Comment by bhanupratapys** [comment]
I just tested these domains with default adblock filter, every single domain was blocked.

DoT : `adblock.dns.dnswarden.com`
DoH: `https://dns.dnswarden.com/adblock`

If you are using custom-filter dns, then please share the domain/url for dns. Also mention the dns client which you are using, might be useful for me to debug further.

**Comment by GiddyGoatGaming** [comment]
https://dns.dnswarden.com/g00osi00000000800ug080o0000000000000000000000000000000000000 Is my config minus the whitelist I use. I use ios native dns management thingy that has been on iOS since iOS 14 if that makes sense. In terms of what server I’m connected to, I’m connected to Toronto’s server

**Comment by GiddyGoatGaming** [comment]
And I don’t think it’s something wrong with my safari or what not because rethink dns and nextdns both can block all these domains.

**Comment by bhanupratapys** [comment]
> https://dns.dnswarden.com/g00osi00000000800ug080o0000000000000000000000000000000000000 Is my config minus the whitelist I use. I use ios native dns management thingy that has been on iOS since iOS 14 if that makes sense. In terms of what server I’m connected to, I’m connected to Toronto’s server

I tested this config on couple of different clients (just android and linux) and all worked correctly. Sorry, I've no idea why you are facing this issue on iOS.

**Comment by GiddyGoatGaming** [comment]
Ok. Il experiment a bit more and see if I can figure out anything that would be the cause of my issue.

**Comment by GiddyGoatGaming** [comment]
Il test on my computer and old phone in a little bit but I just tried with only the goodbye ads filter which I know has a false positive with amp-api-edge.apps.apple.com and it still unblocked that so maybe it isn’t blocking anything altogether. I also tried with the doh and dot ones you sent and kept getting the same results as before on d3ward.

**Comment by GiddyGoatGaming** [comment]
Ok. Just tested on my android phone and windows computer after setting up a good amount of filters bam. Shows 100% blocked. Copied and pasted the same config onto my iOS phone and bam, 90% and the links above dont get blocked. So it’s definitely a ios problem

**Comment by bhanupratapys** [comment]
> _rdns dev here_
> 
> > 90% and the links above dont get blocked. So it's definitely a ios problem
> 
> The code for dnswarden isn't available to see why their adblocking code doesn't work on iOS, as this could be due to multitude reasons (Private Relay, custom DoH within Safari for example; or the DNS server has leaks / bugs).

True, might be any of the reasons you mentioned. I just use tools developed by powerdns guys and haproxy. And a tiny module which is <200 lines of code to incorporate customfilter dns ( i did not try to reinvent the wheel from scratch :blush: )

**Comment by GiddyGoatGaming** [comment]
Seems to be fixed for me right now. If I find it to still be doing it’s job in 24 hours. This issue will be closed
