### ISSUE TITLE
Adblocking seems to be inconsistent

### ISSUE THREAD

**Issue by AdityaGarg8** [bhanupratapys/dnswarden#27]
For sometime, it was blocking ads on Hotstar perfectly but later it isn’t.

I am using a custom configuration, and goodbye ads is the only blocklist that supports Hotstar in my configuration.

https://dns.dnswarden.com/80000080000001c000230000000000000000000000000000000000000000

This is my configuration. I am using this on an iPad Air 5.

I’ve also notices that the DNS resolver name did get changed when it wasn’t blocking ads to ‘CACHENETWORKS’. When it was working perfectly, the name started with an H, but I don’t remember the exact name.

**Comment by AdityaGarg8** [comment]
The score on https://d3ward.github.io/toolz/adblock.html has also reduced to 67%. Previously it was a perfect 100%

**Comment by AdityaGarg8** [comment]
A little update, on my Android phone, the DNS resolver name is being shows as 'NETACTUATE' and it is blocking ads perfectly there.

**Comment by bhanupratapys** [comment]
Might be related to this https://github.com/bhanupratapys/dnswarden/issues/26 .

Could you perform a simple [dnsleak](https://dnsleaktest.com/) test on ipad and check with location it is getting connected to ?

**Comment by AdityaGarg8** [comment]
Update:- I reconnected after sometime on iPad and it blocked ads on hotstar. But again, I'd say there is a bit on inconsistency over here. Can you help me with this?

**Comment by AdityaGarg8** [comment]
I did a dnsleak test

Hello 223.187.97.30
from Ludhiana, India

That’s the output

**Comment by bhanupratapys** [comment]
Thats your ip address (i deleted the comment). Click on Extended test on that page.

**Comment by AdityaGarg8** [comment]
Umm, is the DNS being leaked?

**Comment by AdityaGarg8** [comment]
> Thats your ip address (i deleted the comment). Click on Extended test on that page.

Oh sorry. I’ll do it rn.

**Comment by AdityaGarg8** [comment]
I’m getting this now



103.254.161.138 | None | NetActuate | Chennai, India
-- | -- | -- | --

**Comment by bhanupratapys** [comment]
> I’m getting this now
> 
> 103.254.161.138	None	NetActuate	Chennai, India

Is this on ipad ?

**Comment by AdityaGarg8** [comment]
Looks like it changes netacutate, this was working well for me on Hotstar on my android.

**Comment by AdityaGarg8** [comment]
> > I’m getting this now
> > 103.254.161.138	None	NetActuate	Chennai, India
> 
> Is this on ipad ?

Yes

**Comment by AdityaGarg8** [comment]
And now Ads are being blocked on iPad as well.

**Comment by AdityaGarg8** [comment]
I guess it was CACHENETWORKS causing issues for me till now.

**Comment by AdityaGarg8** [comment]
The ads are back on iPad now

167.88.158.67	unknown.scnet.net.	Deft Hosting	Singapore 

dnsleak test

**Comment by AdityaGarg8** [comment]
And resolve name again is CACHENETWORKS

**Comment by bhanupratapys** [comment]
As the problem is only on iOS devices, i came up with a band-aid solution and deployed it (should atleast circumvent the problem until i find a permanent solution).

Let me know if you face further problems.

**Comment by AdityaGarg8** [comment]
Curious to know, what changes have you done for iOS?

**Comment by bhanupratapys** [comment]
Nothing really specific to ios. I plugged a known problem while using customfilter dns (i don't even know whether its gonna be completely helpful in this case :rofl:)

**Comment by AdityaGarg8** [comment]
Oh ok. I'll ping you if I face any issue then.

**Comment by AdityaGarg8** [comment]
Hi
I tried Hotstar today and unfortunately the issue seems to have increased now. Previously the issue was occasionally seen, now it seems to have become permanent :(

**Comment by AdityaGarg8** [comment]
Looks like the issue is specific to iOS, caus on Android, I haven't been able to reproduce the issue yet.

**Comment by bhanupratapys** [comment]
I've no idea why this is happening on ios. I'm actually flying in blind here, I've a Mac but not the ipad/iPhone to test on. 

If you could answer the following things which might be helpful to pinpoint the problem. 

- Are you using any of the 3rd party apps to connect to the dns? 
- Are you using apple private / iCloud relays? 
- Are you using any Vpn's?
- Could you just use default adblock filter `https://dns.dnswarden.com/adblock` and see if you are facing the same problem?

**Comment by AdityaGarg8** [comment]
No to first 3 questions

I use https://dns.notjakob.com/tool.html to create iOS profiles for DNS.

I tried the default filter but ads on Hotstar are still visible.

**Comment by AdityaGarg8** [comment]
On Android I use Intra for DoH, just in case it's relevant to you.

**Comment by AdityaGarg8** [comment]
Also, in iOS, it's not that it is completely ineffective, it blocks certain ads , but complete blocking isn't present, like hotstar.

**Comment by AdityaGarg8** [comment]
I tried AdGuard and nextdns on iOS, they seem to be working good, so I guess it's not that iOS isn't capable?

**Comment by bhanupratapys** [comment]
> I tried AdGuard and nextdns on iOS, they seem to be working good, so I guess it's not that iOS isn't capable?

Then it looks like a filterlist problem (I also use a separate whitelist, so that frequently used top websites doesn't break often)

**Comment by AdityaGarg8** [comment]
> Then it looks like a filterlist problem (I also use a separate whitelist, so that frequently used top websites doesn't break often)

I had not enabled whitelist in my configuration.

**Comment by bhanupratapys** [comment]
> I had not enabled whitelist in my configuration.

Alright, can you take a screenshot when a ad gets played on hotstar?

**Comment by AdityaGarg8** [comment]
> > I had not enabled whitelist in my configuration.
> 
> Alright, can you take a screenshot when a ad gets played on hotstar?

Well it ad gets displayed first, then the show starts.

**Comment by AdityaGarg8** [comment]
https://ibb.co/W2sj7C3
https://ibb.co/FJzw23J

**Comment by bhanupratapys** [comment]
> https://ibb.co/W2sj7C3 https://ibb.co/FJzw23J

Thank you, looking into it.

**Comment by bhanupratapys** [comment]
I noticed that you were using one of energized list (broken since a week) and goodbyeads (which hasn't been updated in 3 weeks)

Could you switch to default filter and try once again? I think [this](https://github.com/dnswarden/blocklist-staging/commit/68679bf48db9f003430dfdc2538a800c01172f42) should fix it for default filter.

OR

Choose a list which contains `hesads.akamaized.net` in them, you can search it [here](https://dnswarden.com/search.html) .

**Comment by AdityaGarg8** [comment]
Unfortunately the default list doesn’t block the ads.

IMO it’s only goodbye ads that has successfully blocked ads in Hotstar for me till now.

AdGuard doesn’t support goodbye ads, so I had made a custom blocklist for Hotstar there. Should I share it with you?

**Comment by AdityaGarg8** [comment]
Maybe you could add it as Hotstar list or something?

**Comment by bhanupratapys** [comment]
> Unfortunately the default list doesn’t block the ads.
> 
> IMO it’s only goodbye ads that has successfully blocked ads in Hotstar for me till now.
> 
> AdGuard doesn’t support goodbye ads, so I had made a custom blocklist for Hotstar there. Should I share it with you?

Did you try the default filter now? I made the changes to it just couple of hours ago.

**Comment by bhanupratapys** [comment]
> Maybe you could add it as Hotstar list or something?

Sure, I'll have a look at it.

**Comment by AdityaGarg8** [comment]
https://www.transfernow.net/dl/20221202p9Wp8ErS

Here you go

**Comment by AdityaGarg8** [comment]
> > Unfortunately the default list doesn’t block the ads.
> > IMO it’s only goodbye ads that has successfully blocked ads in Hotstar for me till now.
> > AdGuard doesn’t support goodbye ads, so I had made a custom blocklist for Hotstar there. Should I share it with you?
> 
> Did you try the default filter now? I made the changes to it just couple of hours ago.

Yes I tried it now

**Comment by AdityaGarg8** [comment]
> https://www.transfernow.net/dl/20221202p9Wp8ErS
> 
> Here you go

I hosted it as a gist

https://gist.github.com/AdityaGarg8/ad87f0f6f6a1f785df3e1e1a885afaa0

**Comment by bhanupratapys** [comment]
> > https://www.transfernow.net/dl/20221202p9Wp8ErS
> > Here you go
> 
> I hosted it as a gist
> 
> https://gist.github.com/AdityaGarg8/ad87f0f6f6a1f785df3e1e1a885afaa0

It's live, head over to customfilter configuration page and choose `dnswarden (blacklist extreme)` (which should be at the end) and along with your lists.

**Comment by AdityaGarg8** [comment]
I made a new configuration

https://dns.dnswarden.com/g00001000000014000210040000000000000000000000000000000000000

It's exactly the same as I have in AdGuard. But unfortunately, the issue still persists.

It did got ads blocked in the first attempt on my iPad, but after that it failed again :(

Maybe we could try making something like Blocklist ultimate? Maybe a single Blocklist may fix the issues? The settings I have done above block all the ads on all OTT platforms atleast in India.

**Comment by AdityaGarg8** [comment]
P.S. I am also facing issues in Android now.

**Comment by AdityaGarg8** [comment]
On Android it works good though.

**Comment by AdityaGarg8** [comment]
I tried applying just the `blacklist extreme` but still ads were not blocked on Hotstar on iOS:(

**Comment by bhanupratapys** [comment]
> Maybe we could try making something like Blocklist ultimate? Maybe a single Blocklist may fix the issues? The settings I have done above block all the ads on all OTT platforms atleast in India.

Nah, it doesn't matter if its a single list or multiple lists. It doesn't affect the blocking mechanism.


> I tried applying just the `blacklist extreme` but still ads were not blocked on Hotstar on iOS:(

Yeah, you gotta use other blocklists along with extreme to make it work effectively.




> On Android it works good though.

That's a mystery :rofl:. Dns server doesn't distinguish between android/ios/windows machines, it blocks anything if it is defined in a rule.

Could you try out [this](https://apps.apple.com/us/app/dnscloak-secure-dns-client/id1452162351) app and test it? Might be tricky to setup initially :sweat_smile:

**Comment by GiddyGoatGaming** [comment]
> > Maybe we could try making something like Blocklist ultimate? Maybe a single Blocklist may fix the issues? The settings I have done above block all the ads on all OTT platforms atleast in India.
> 
> Nah, it doesn't matter if its a single list or multiple lists. It doesn't affect the blocking mechanism.
> 
> > I tried applying just the `blacklist extreme` but still ads were not blocked on Hotstar on iOS:(
> 
> Yeah, you gotta use other blocklists along with extreme to make it work effectively.
> 
> > On Android it works good though.
> 
> That's a mystery 🤣. Dns server doesn't distinguish between android/ios/windows machines, it blocks anything if it is defined in a rule.
> 
> Could you try out [this](https://apps.apple.com/us/app/dnscloak-secure-dns-client/id1452162351) app and test it? Might be tricky to setup initially 😅

Sorry for swooping in here but is there a way to input a custom dns into dns cloak or is it just the available servers that are listed? I’m having trouble finding a way to input a doh or dot address other then selecting a listed dns server

**Comment by AdityaGarg8** [comment]
> Sorry for swooping in here but is there a way to input a custom dns into dns cloak or is it just the available servers that are listed? I’m having trouble finding a way to input a doh or dot address other then selecting a listed dns server

Even I am facing this issue 😅

**Comment by AdityaGarg8** [comment]
I did find something relevant from this app though.

This app has a strict mode, which says that iOS has a behaviour to fall back to default system resolver in case of a failed request.

That mode basically disables this behaviour.

**Comment by bhanupratapys** [comment]
> Sorry for swooping in here but is there a way to input a custom dns into dns cloak or is it just the available servers that are listed? I’m having trouble finding a way to input a doh or dot address other then selecting a listed dns server


> Even I am facing this issue sweat_smile


It should be possible to do it with stamps generated from [here](https://dnscrypt.info/stamps/).

Or use this [another app](https://apps.apple.com/us/app/dns-changer-trust-dns/id1498090025), it has easier way to add custom servers.

**Comment by AdityaGarg8** [comment]
Maybe you need to fake resolve the requests on iOS?

**Comment by AdityaGarg8** [comment]
It seems to block more ads now, at least the percentage of ads blocked and risen to 94 from 71 on online testing.

But, Hotstar app hates VPNs :(

**Comment by GiddyGoatGaming** [comment]
Ok, so I tested it with the adultfilter dns that is in dns cloak and I got the same result as my situation. What i find is that dnswarden can sometimes initially block the domain but once you reload the page, it doesn’t block it again. Weird

**Comment by AdityaGarg8** [comment]
Something similar is my situation as well.

**Comment by GiddyGoatGaming** [comment]
Using adguard dns, trust dns, and dns cloak all give me the same result:(

**Comment by bhanupratapys** [comment]
> But, Hotstar app hates VPNs :(

You should be fine i think, those apps doesn't change your IP address.

**Comment by AdityaGarg8** [comment]
Hotstar is complaining of VPN is use :(

**Comment by AdityaGarg8** [comment]
> Using adguard dns, trust dns, and dns cloak all give me the same result:(

Here you mean by AdGuard dns filter?

**Comment by bhanupratapys** [comment]
> Ok, so I tested it with the adultfilter dns that is in dns cloak and I got the same result as my situation. What i find is that dnswarden can sometimes initially block the domain but once you reload the page, it doesn’t block it again. Weird. Il try more things.



> Using adguard dns, trust dns, and dns cloak all give me the same result:(

I've no idea why this happens on ios  :sob:

**Comment by AdityaGarg8** [comment]
Any way to get an ipv4 variant of the DNS?

**Comment by bhanupratapys** [comment]
> Any way to get an ipv4 variant of the DNS?

No, not unless I remove ipv6 records.

**Comment by AdityaGarg8** [comment]
I got another website named https://ahadns.com/ which has similar functionality as dns warden and this seems to work for me.

Maybe you could see something is different in their setup causing issues for us?

@GiddyGoatGaming , could you try AhaDNS and see if it works for you or not?

**Comment by GiddyGoatGaming** [comment]
I have tried ahadns and it has worked. I’ve also tried with nextdns and rethinkdns and they work.

**Comment by AdityaGarg8** [comment]
Rethink is something new. I’ll try it.

But, dns warden should work too ….

**Comment by GiddyGoatGaming** [comment]
the downside with rethinkdns is the lack of whitelists which is very important when you want to use instagram and Facebook. That’s what dnswarden excels at. Rethinkdns has been improving a lot over the past months and I’m trying to get a bunch of lists over there that would do well but it’s tough with the activity of the devs some days. I don’t even consider using nextdns anymore due to the lack of growth with blocklists and such.

**Comment by AdityaGarg8** [comment]
@bhanupratapys , there is something special in ios that maybe you are lacking then?

iOS has a behaviour to fall back to default system resolver in case of a failed request, I suppose?

**Comment by AdityaGarg8** [comment]
I just realised rethink has an advanced blockist option as well, and it works for me as well.

@GiddyGoatGaming , if you know any other DNS providers with custom filter options, do share.

**Comment by GiddyGoatGaming** [comment]
That’s all i know at the current point in time. There is controld but it costs money for some features and is just not that good. I personally think it’s overrated😂

**Comment by bhanupratapys** [comment]
> The stinking green checkmark on the website is there. So it definitely recognizes dnswarden as my dns provider. Just not with blocking

Yup, that definitely looks a filtering problem. I think i fixed it, but i need someone to confirm it.

**Comment by AdityaGarg8** [comment]
Well, it seems to work now on iOS 🥳

I’ll test it for a few days, and if I face any issue, I’ll mention it, else I’ll close this issue.

@GiddyGoatGaming , can you test this as well?

and @bhanupratapys , thanks a lot for your help and this project!

**Comment by AdityaGarg8** [comment]
BTW, what was causing issues on iOS?

**Comment by GiddyGoatGaming** [comment]
Ain’t no fricking way. It’s working for me too @AdityaGarg8 . Well my day is made

**Comment by AdityaGarg8** [comment]
Yeah now I have 5 servers lol

**Comment by bhanupratapys** [comment]
> BTW, what was causing issues on iOS?

TYPE 65 queries :laughing:,human error. Didn't realise i had removed these kind of queries from filtering logic.

  

> Yeah now I have 5 servers lol

What do you mean?

**Comment by ignoramous** [comment]
> BTW, what was causing issues on iOS?

My guess would be DNSWarden now properly blocks the HTTPS/SVCB records (in addition to A/CNAME/AAAA).

**Comment by AdityaGarg8** [comment]
> What do you mean?

In an attempt to get a working AdBlocker, I ended up getting 4 more apart from DNSWarden.

**Comment by AdityaGarg8** [comment]
BTW, not related to this, but has anyone noticed goodbye ads breaks the App Store. Any idea which domain to be whitelisted?

**Comment by GiddyGoatGaming** [comment]
@AdityaGarg8 its been like that for months. Like since July at least. I don’t know how it hasn’t been fixed yet😭. It’s just a single domain that needs to be whitelisted

**Comment by bhanupratapys** [comment]
> My guess would be DNSWarden now properly blocks the HTTPS/SVCB records (in addition to A/CNAME/AAAA).

Haha, true. Couple of days ago i tweaked my filtering logic to only filter A/AAAA/CNAME type queries :man_facepalming:

**Comment by AdityaGarg8** [comment]
> @AdityaGarg8 its been like that for months. Like since July at least. I don’t know how it hasn’t been fixed yet😭. It’s just a single domain that needs to be whitelisted. Which is amp-api-edge.apps.apple.com

Thanks, it’s fixed now :)
