### ISSUE TITLE
New Malicious Domain Blocklist

### ISSUE THREAD

**Issue by manic-code** [bhanupratapys/dnswarden#33]
Hi there, 

Really appreciate your website's tool for searching all the major blocklists. I recently created a new list that is tailored to new and unknown malicious domains no other major blocklist has blacklisted. I'll link it here so you can examine it, if you think it's worthy of being included amongst the existing lists on your search tool that'd be pretty neat! 

https://github.com/manic-code/Emerging-Malicious-Domain-Blocklist

**Comment by bhanupratapys** [comment]
Website's search tool uses/displays only lists which are used by dnswarden project, you can find it [here](https://github.com/dnswarden/blocklist-staging). Let me see what i can do about it.
