### ISSUE TITLE
Only QUIC with custom filter and DNSCrypt works, everything else fail

### ISSUE THREAD

**Issue by tina-hello** [bhanupratapys/dnswarden#36]
Testing with https://github.com/ameshkov/dnslookup, the Adblock, Uncensored, and Adult-Filter variants of DoT, DoH, and DoQ all fail, custom filter only works with DoQ, while DoT and DoH fail, DNSCrypt works.

**Comment by bhanupratapys** [comment]
I just tested it out on the latest dnslookup binary and everything works. I get the responses for both the protocols,

`./dnslookup google.com tls://g00004000001000004.dns.dnswarden.com`

`./dnslookup google.com https://dns.dnswarden.com/000004000001000004`

**Comment by tina-hello** [comment]
Yeah can confirm it now works.
