### ISSUE TITLE
Broken page elements when using dnswarden doh on firefox

### ISSUE THREAD

**Issue by anxiouslelimo** [bhanupratapys/dnswarden#37]
Tried with uncensored, adblock, adult-filter and custom filters using Hagezi Multi Normal, Hagezi TIF and OISD NSFW.
theverge.com doesn't load images until refreshed again. Brave search page is completely broken. These are the only two webpages visited and probably the issue affects other webpages too. 

![Screenshot 2023-11-26 at 15-54-04 Brave Search](https://github.com/bhanupratapys/dnswarden/assets/115996455/0b7395e4-d0eb-42a0-997d-0a8c4c53f5bd)
<img width="890" alt="Screenshot 2023-11-26 155355" src="https://github.com/bhanupratapys/dnswarden/assets/115996455/306314a3-cf24-482f-aa85-d80a8224df9d">

**Comment by bhanupratapys** [comment]
Hello! I think the problem with verge is fixable by increasing the timeouts of the resolver. I couldn't find any problem on [Brave](https://search.brave.com) search page, could you re-confirm it regarding this?

**Comment by anxiouslelimo** [comment]
> Hello! I think the problem with verge is fixable by increasing the timeouts of the resolver. I couldn't find any problem on [Brave](https://search.brave.com) search page, could you re-confirm it regarding this?

I am facing this issue in firefox on desktop. using the same configuration in brave (android) doesnt cause this issue.
