### ISSUE TITLE
Does the DNS server block requests from data center and VPN IPs?

### ISSUE THREAD

**Issue by tina-hello** [bhanupratapys/dnswarden#39]
When the VPN (both self-hosted on VPS and third party product) is enabled

```
dnslookup google.com https://dns.dnswarden.com/adblock
dnslookup 1.11.1-11969
2024/08/23 14:27:25 [fatal] Cannot make the DNS request: requesting https://dns.dnswarden.com:443/adblock: Get "https://dns.dnswarden.com:443/adblock?dns=AAABAAABAAAAAAAABmdvb2dsZQNjb20AAAEAAQ": tls: handshake message of length 144076 bytes exceeds maximum of 65536 bytes
```

This happens with the DoT, DoQ & DoH endpoints. Works just fine without a VPN.

**Comment by bhanupratapys** [comment]
dnswarden doesn't block or differentiate between vps or vpn's. 

Fault lies here, ` tls: handshake message of length 144076 bytes exceeds maximum of 65536 bytes`
