### ISSUE TITLE
Namecoin / Emercoin support

### ISSUE THREAD

**Issue by wuniversales** [bhanupratapys/dnswarden#7]
Would it be possible to add support for Namecoin / Emercoin?
Thanks greetings

**Comment by bhanupratapys** [comment]
Gonna close this now, might look into this in the future.

**Comment by Karlson2k** [comment]
Seems that .lib domains are not working (checked `nnm-club.lib` and `flibusta.lib`), while OpenNIC domains are working.

**Comment by bhanupratapys** [comment]
@Karlson2k Should be working it. I need to setup additional tests to encounter these types of problems. Reopen the issue if you find anything broken again.

**Comment by Karlson2k** [comment]
@bhanupratapys Confirming, `.lib` is working now.
Thanks for super-quick fix.

**Comment by tina-hello** [comment]
Seems EthDNS is not working, `dnslookup ens.eth https://dns.dnswarden.com/` returns NXDOMAIN.
