### ISSUE TITLE
Block adult content

### ISSUE THREAD

**Issue by wuniversales** [bhanupratapys/dnswarden#8]
Would it be possible to add another DNS to block adult content?

It would be great to block adult content and in turn block advertising.

Good job, regards

**Comment by bhanupratapys** [comment]
Easy to implement it. Are there any good adult content filter lists available?

**Comment by wuniversales** [comment]
You can use this project 
https://github.com/StevenBlack/hosts
The project also has other filters, you may want to add more.

**Comment by bhanupratapys** [comment]
Just a update on this. Initially it will be supported for dot, doh and dnscrypt. It's gonna block adult content (around 30k domains) plus other domains which are present in adblock dns. Along with that, it is gonna enforce safe search for Google, Bing, YouTube, duckduckgo and yandex. 

NOT YET LIVE 
DoT : adult-filter-dot.dnswarden.com
DoH : https://doh.dnswarden.com/adult-filter
Dnscrypt : Todo

**Comment by bhanupratapys** [comment]
Finally implemented it. [Read me](https://github.com/bhanupratapys/dnswarden/blob/master/README.md) should have more info regarding the configuration details.

**Comment by gloschtla** [comment]
I love dnswarden's project.
