### ISSUE TITLE
Redirect to http to https version?

### ISSUE THREAD

**Issue by wuniversales** [bhanupratapys/dnswarden#9]
I don't know if this will be possible, but is it possible to add filters to redirect to the https site?
I say this to avoid installing "https everywhere" or similar add-ons.
Thank you

**Comment by beerisgood** [comment]
That would require a huge list with every HTTP site
Don't think the work is worth it.

Most sites and all important sites, already use HTTPS

**Comment by bhanupratapys** [comment]
> I don't know if this will be possible, but is it possible to add filters to redirect to the https site?
> I say this to avoid installing "https everywhere" or similar add-ons.
> Thank you

Sorry, this isn't possible with dns. You definitely need a client side solution for http to https redirection.
